ci: rebase when pushing nats in upgrade-go1.x
fixes:
```bash
put: nats-release
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
To github.com:cloudfoundry/nats-release.git
 ! [rejected]        HEAD -> develop (fetch first)
error: failed to push some refs to 'git@github.com:cloudfoundry/nats-release.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```